# Jekyll Configuration
title: "clubSandwich Intern Resources"
description: "Getting Started Guide for clubSandwich Interns"
baseurl: "/clubSandwichResources"  # Must match your repository name
url: "https://pekofsky.github.io"  # Your GitHub Pages domain

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Exclude files from being processed
exclude:
  - .Rproj.user/
  - .Rhistory
  - .git/
  - .gitignore
  - Getting Started For Interns.Rmd

# Default layouts for different types of content
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
