# Jekyll Configuration
title: "clubSandwich Intern Resources"
description: "Resources for clubSandwich Interns"
baseurl: "/clubSandwichResources"  # Must match your repository name
url: "https://pekofsky.github.io"  # Your GitHub Pages domain

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Collections
collections:
  pages:
    output: true

# Exclude files from being processed
exclude:
  - .Rproj.user/
  - .Rhistory
  - .git/
  - .gitignore
  - clubSandwichResources.Rproj
  - Getting Started For Interns.Rmd
  - Getting-Started-For-Interns.pdf

# Default layouts for different types of content
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
